App_Order/urls.py
from django.urls import path
from App_Order import views
app_name="App_Order"

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='adds'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
    path('cart/',views.cart_view,name='cart'),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name="App_Shop"

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(),name='product_detail'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

#to show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Category(models.Model):
    title =models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural="Categories"


class Product(models.Model):
    mainimage =models.ImageField(upload_to='products')
    name= models.CharField(max_length=264)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category')
    preview= models.TextField(max_length=200,verbose_name='preview_text')
    detailed_text=models.TextField(max_length=1000,verbose_name='description')
    price=models.FloatField()
    old_price=models.FloatField(default=0.00)
    created =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
#minus means latest will go first
        ordering = ['-created',]

App_Shop/views.py
from django.shortcuts import render

#importing a list
from django.views.generic import ListView,DetailView

#models
from App_Shop.models import Product

#mixin
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

#will create a classbased view
class Home(ListView):
    model = Product
    template_name='App_Shop/home.html'

#this also be a classbased view
class ProductDetail(LoginRequiredMixin,DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

templates/App_Shop/home.html
{% extends 'base.html' %}

{% block title %} Ecommerce homepage {% endblock %}

{% block body %}
<div class="container my-5">
<h2 class="my-5">Featured Product</h2>
<div class="row">
  {% for product in object_list %}
  <div class="col-md-6 col-sm-12 col-lg-3">
    <figure class="card card-product">
      <div class="img-wrap">
        <img src="/media/{{product.mainimage}}" style="width:100%;height:300px;">
      </div>
      <figcaption class="info-wrap">
        <h6 class="title" ><a href="{%url 'App_Shop:product_detail' pk=product.pk%}">{{product.name}}</a></h6>
        <div class="action-wrap">
          <div class="price-wrap h5">

            <span class="price-new">&#2547;{{product.price|floatformat:2}}</span>
            <span class="price-old"><strike>&#2547;{{product.old_price|floatformat:2}}</strike></span>
          </div>
        </div>
      </figcaption>
    </figure>
  </div>
  {% endfor %}
</div>
</div>
<div class="">

</div>
{% endblock %}

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.detailed_text|linebreaks}}</p>
            </dd>
          </dl>
          <a href="{% url 'App_Order:adds' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}