App_Login/urls.py
from django.urls import path
from App_Login import views
app_name="App_Login"

urlpatterns = [
    path('signup/', views.sign_up,name='signup'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.user_profile,name='profile'),

]

App_Order/urls.py
from django.urls import path
from App_Order import views
app_name="App_Order"

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='adds'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
    path('cart/',views.cart_view,name='cart'),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name="App_Shop"

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(),name='product_detail'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

#to show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title %} E-commerce app by sazid {% endblock %}</title>
  <style>
  .card {
    height: 350px;
  }

  .card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden;
  }
  .card-product .price-new, .card-product .price {
    margin-right: 5px;
  }

  .card-product .price-old {
    color: #999;
  }

  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center;
  }

  .card-product .img-wrap img {
    max-height: 100%;
    max-width: 100%;
    object-fit: cover;
  }

  .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px;
  }

  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .title {
    margin-top: 0px;
  }

  </style>
</head>
<body>
  {% include 'navbar.html' %}
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block body %} {% endblock %}

  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'App_Shop:home' %}">E-commerce Project</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
              <a href="{% url 'App_Order:cart' %}" class="nav-link">
                <i class="fa fa-shopping-cart"></i> Cart
                <span class="badge badge-light">{{ request.user | cart_total }}</span>
              </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
        </li>
        {% endif %}
      </ul>
  </div>
</div>
</nav>